# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class EventType(Enum):

    all = "$all"
    traces = "traces"
    custom_events = "customEvents"
    page_views = "pageViews"
    browser_timings = "browserTimings"
    requests = "requests"
    dependencies = "dependencies"
    exceptions = "exceptions"
    availability_results = "availabilityResults"
    performance_counters = "performanceCounters"
    custom_metrics = "customMetrics"
